---
- name: Hello World!
  hosts: all

  vars:
    my_string: This is my string abc abc 

  tasks:
  
    # Set a default value for the summary. Any changes will change it from this. 
    - name: Interlace variable
      debug:
        msg: '{{ destination_email }}'
        
    # Set a default value for the summary. Any changes will change it from this. 
    - name: Interlace variable
      debug:
        msg: "{{ destination_name }} <{{ destination_email }}>"

    # Set a default value for the summary. Any changes will change it from this. 
    - name: String is twice
      debug: msg='There were two abc in the string'
      when: (my_string|regex_findall('abc')|length) == 2
      
    # Set a default value for the summary. Any changes will change it from this. 
    - name: String is not twice
      debug: msg='There were NOT two abc in the string'
      when: (my_string|regex_findall('abc')|length) != 2
