# There are 3 different server types.
# Each running different services
# Each of the 3 has different service states

#servers_dcc:
#  - 
#  -
#servers_storefront:
#  -
#  -
#servers_pvs:
#  -
#  -

# Create 3 server lists. These can be overridden in the template variables

---
- name: Hello World!
  hosts: all

  vars:
    servers_storefront: []
    servers_dcc: []
    servers_pvs: []

  tasks:
      
    # Create a temp folder to store all the information
    - name: Create temp folder
      file:
        path: /tmp/MyTest
        state: directory
      delegate_to: 127.0.0.1
      run_once: true

    # Create a temporary file to store the text information from all tests
    - name: Creating an empty file to store the single summary
      copy:
        dest: "/tmp/MyTest/Summary.txt"
        content: All okay
      delegate_to: 127.0.0.1
      run_once: true
    
    # Create a temporary file to store the text information from all tests
    - name: Creating an empty file to store the query results
      file:
        path: "/tmp/MyTest/Results.txt"
        state: touch
      delegate_to: 127.0.0.1
      run_once: true

    # Carryout custom checks only on servers in the storefront list
    - name: Check store_front
      include_tasks: tasks/Check_StoreFront.yml
      # when: ansible_hostname in servers_storefront
      
    # Carryout custom checks only on servers in the dcc list
    - name: Check store_front
      include_tasks: tasks/Check_DCC.yml
      # when: ansible_hostname in servers_dcc
      
    # Carryout custom checks only on servers in the pvs list
    - name: Check store_front
      include_tasks: tasks/Check_PVS.yml
      # when: ansible_hostname in servers_pvs

    # Read all the information from the temporary file and copy it into a fact
    - name: read information from file for 
      set_fact:
        file_summary: "{{ lookup('file', '/tmp/MyTest/Summary.txt') }}"
      run_once: true
      delegate_to: 127.0.0.1

    # Read all the information from the temporary file and copy it into a fact
    - name: read information from file
      set_fact:
        file_results: "{{ lookup('file', '/tmp/MyTest/Results.txt') }}"
      run_once: true
      delegate_to: 127.0.0.1

    # Print output to Ansible tower
    - name: Print version
      debug:
        msg: 
          - "Service summary: {{ file_summary }}"
          - "Status: {{ file_results }}"
      run_once: true

  # Send email using SMTP
  #- name: email information
  #  mail:
  #    host: 
  #    port: 25
  #    to: Chris Vickers <john.smith@example.com>
  #    subject: "Server status '{{ service_summary }}'"
  #    body: '{{ file_text }}'
  #  delegate_to: localhost
  #  run_once: true
