---
  
#  - name: Set facts to empty
#    set_facts:
#      status_of_services_running:
#      status_of_services_stopped:
#      status_unregistered_hosts:

  # Services Expected (Expected behaviour: Running) ------------------------------------------------------------------------------------------------
  - name: Query using powershell to get services that should be running
    win_shell: echo 'Test'
    register: status_of_services_running


  - name: Write Powershell response to file
    lineinfile:
      path: "/tmp/MyTest/Results.txt"
      line: |
        "Service Status for host '{{ ansible_hostname }}'"
        "{{ status_of_services_running.stdout }}"
        ""
        ""
      insertafter: EOF
    delegate_to: 127.0.0.1
    
  # Services (Expected behaviour: Stopped) ---------------------------------------------------------------------------------------------------------
  - name: Query using powershell to get services that should be stopped
    win_shell: echo 'stopped stopped'
    register: status_of_services_stopped

  - name: Write summary service status to file
    lineinfile:
      path: "/tmp/MyTest/Results.txt"
      line: |
        "Service Status for host '{{ ansible_hostname }}'"
        "{{ status_of_services_running.stdout }}"
        ""
        ""
      insertafter: EOF
    delegate_to: 127.0.0.1

  # Unregistered hosts ------------------------------------------------------------------------------------------------------------------
  - name: Check for unregistered hosts
    win_shell: echo 'All the powered-on VMs are registered succcessfully!'
    register: status_unregistered_hosts

  # Write a unregistered hosts to file
  - name: Write summary to file
    lineinfile:
      path: "/tmp/MyTest/Results.txt"
      line: |
        "Unregistered hosts output '{{ ansible_hostname }}'"
        "{{ status_unregistered_hosts.stdout }}"
        ""
        ""
      insertafter: EOF
    delegate_to: 127.0.0.1

  # Write summary to file if any value is not correct ---------------------------------------------------------------------------------
  - name: Write detailed results to temporary file
    lineinfile:
      path: "/tmp/MyTest/Summary.txt"
      line: "Error found"
      # insertafter: EOF
    delegate_to: 127.0.0.1
    when: |
      status_of_services_running is search("stopped")
      or
      "All the powered-on VMs are registered succcessfully!" not in status_unregistered_hosts.stdout
      or
      ((status_of_services_stopped | regex_findall('stopped') | length) != 2)

